### ISSUE TITLE
Nothing visible in VR

### ISSUE THREAD

**Issue by leefogg** [hdonk/lwjgl_vr_framework#1]
When program runs, a new window opens, SteamVR opens and displays "Now Playing: Java" but the is rendering the loading area with said text. The actual render of the rotating axis thing does not show in VR.

**Comment by hdonk** [comment]
I'll fire it up and have a look.

**Comment by hdonk** [comment]
I think you've run in to the problem I found - there's no support for GLES with VR. I moved over to using GL in the OpenGL branch, and that works fine for me.
